apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: app
  template:
    metadata:
      labels:
        app: nginx
        tier: app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
            

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    tier: app
spec:
  type: NodePort
  selector:
    app: nginx
    tier: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
