apiVersion: v1
kind: Pod
metadata:
  name: nginx-resources
  namespace: dev-environment
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
      imagePullPolicy: Always