apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mysql
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mysql
    spec:
      containers:
      - name: mysql
        image: raja1475/mysql:25
        envFrom:
        - secretRef:
            name: mysql-secret

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    tier: db
    component: mysql
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
    protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: roboshop
type: Opaque
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "eWVzCg==" # base64 encoded value of 'yes'
  MYSQL_DATABASE: "Y2l0aWVzCg=="        # base64 encoded value of 'cities'
  MYSQL_USER: "c2hpcHBpbmcK"         # base64 encoded value of 'shipping'
  MYSQL_PASSWORD: "Um9ib1Nob3BAMQo=" 