apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      app: nginx
  template:
    metadata:
      labels:
        project: roboshop
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80