apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx:{{ .Values.deployment.appVersion }}"
  labels:
    project: roboshop
    app: nginx
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      app: nginx
  template:
    metadata:
      labels:
        project: roboshop
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "nginx:{{ .Values.deployment.appVersion }}"
        ports:
        - containerPort: 80