apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mongodb
  labels:
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
    spec:
      containers:
        - name: mongodb
          image: raja1475/mongodb:25

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    project: roboshop
    tier: db
  ports:
    - name: mongodb-port
      protocol: TCP
      port: 27017
      targetPort: 27017
